apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: docker.io/motaung/udagram-api-feed:v0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 700m
          requests:
            cpu: 250m